language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gordonwh/multi-docker -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true gordonwh/multi-docker npm test

after_success:
    - docker build -t gordonwh/multi-client ./client
    - docker build -t gordonwh/multi-nginx ./nginx
    - docker build -t gordonwh/multi-server ./server
    - docker build -t gordonwh/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push gordonwh/multi-client
    - docker push gordonwh/multi-nginx
    - docker push gordonwh/multi-server
    - docker push gordonwh/multi-worker


