language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gordonwh/multi-docker -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true gordonwh/react-test npm test

after_success:
    - docker build -t gordonwh/multi-client ./client
    - docker build -t gordonwh/multi-nginx ./nginx
    - docker build -t gordonwh/multi-server ./server
    - docker build -t gordonwh/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push gordonwh/multi-client
    - docker push gordonwh/multi-nginx
    - docker push gordonwh/multi-server
    - docker push gordonwh/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-364061318646"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
 
